# Generated by Django 4.2.3 on 2023-09-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_and_time',
            new_name='date',
        ),
    ]
